---
abstract: 'Author tests making sure correct line endings are used'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Test::DZil: 0
  Test::More: 0.88
  Test::Script: 1.05
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.132140'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-EOL
no_index:
  file:
    - perlcritic.rc
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Test::EOL: 1.1
  namespace::autoclean: 0
resources:
  bugtracker: https://github.com/xenoterracide/dist-zilla-plugin-test-eol/issues
  homepage: https://metacpan.org/dist/Dist-Zilla-Plugin-Test-EOL
  repository: git://github.com/xenoterracide/dist-zilla-plugin-test-eol.git
version: 0.08
