---
abstract: 'Author tests making sure correct line endings are used'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::Util: '0'
  Test::DZil: '0'
  Test::More: '0'
  Test::Script: '1.05'
  perl: '5.006'
  strict: '0'
  version: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Test-EOL
no_index:
  directory:
    - corpus
  file:
    - perlcritic.rc
provides:
  Dist::Zilla::Plugin::Test::EOL:
    file: lib/Dist/Zilla/Plugin/Test/EOL.pm
    version: '0.12'
requires:
  Dist::Zilla: '5'
  Dist::Zilla::Plugin::InlineFiles: '0'
  Dist::Zilla::Role::TextTemplate: '0'
  Moose: '0'
  Test::EOL: '1.1'
  namespace::autoclean: '0'
resources:
  bugtracker: https://github.com/xenoterracide/dist-zilla-plugin-test-eol/issues
  homepage: https://metacpan.org/dist/Dist-Zilla-Plugin-Test-EOL
  repository: git://github.com/xenoterracide/dist-zilla-plugin-test-eol.git
version: '0.12'
x_contributors:
  - 'Olivier Mengué <dolmen@cpan.org>'
  - 'Shlomi Fish <shlomif@shlomifish.org>'
