use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006007
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Florian
Ragwitz
rafl
Caleb
Cushing
xenoterracide
Olivier
Mengué
dolmen
Shlomi
Fish
shlomif
lib
Dist
Zilla
Plugin
Test
EOL
